/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuracleCreateRouteImport } from './routes/auracle.create'
import { Route as AuracleIdRouteImport } from './routes/auracle.$id'
import { Route as AuraIdRouteImport } from './routes/aura.$id'
import { Route as ArtistHandleRouteImport } from './routes/artist.$handle'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuracleCreateRoute = AuracleCreateRouteImport.update({
  id: '/auracle/create',
  path: '/auracle/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuracleIdRoute = AuracleIdRouteImport.update({
  id: '/auracle/$id',
  path: '/auracle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraIdRoute = AuraIdRouteImport.update({
  id: '/aura/$id',
  path: '/aura/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistHandleRoute = ArtistHandleRouteImport.update({
  id: '/artist/$handle',
  path: '/artist/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/farm': typeof FarmRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/artist/$handle': typeof ArtistHandleRoute
  '/aura/$id': typeof AuraIdRoute
  '/auracle/$id': typeof AuracleIdRoute
  '/auracle/create': typeof AuracleCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/farm': typeof FarmRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/artist/$handle': typeof ArtistHandleRoute
  '/aura/$id': typeof AuraIdRoute
  '/auracle/$id': typeof AuracleIdRoute
  '/auracle/create': typeof AuracleCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/farm': typeof FarmRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/artist/$handle': typeof ArtistHandleRoute
  '/aura/$id': typeof AuraIdRoute
  '/auracle/$id': typeof AuracleIdRoute
  '/auracle/create': typeof AuracleCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/farm'
    | '/generating'
    | '/onboarding'
    | '/artist/$handle'
    | '/aura/$id'
    | '/auracle/$id'
    | '/auracle/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/farm'
    | '/generating'
    | '/onboarding'
    | '/artist/$handle'
    | '/aura/$id'
    | '/auracle/$id'
    | '/auracle/create'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/farm'
    | '/generating'
    | '/onboarding'
    | '/artist/$handle'
    | '/aura/$id'
    | '/auracle/$id'
    | '/auracle/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  FarmRoute: typeof FarmRoute
  GeneratingRoute: typeof GeneratingRoute
  OnboardingRoute: typeof OnboardingRoute
  ArtistHandleRoute: typeof ArtistHandleRoute
  AuraIdRoute: typeof AuraIdRoute
  AuracleIdRoute: typeof AuracleIdRoute
  AuracleCreateRoute: typeof AuracleCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auracle/create': {
      id: '/auracle/create'
      path: '/auracle/create'
      fullPath: '/auracle/create'
      preLoaderRoute: typeof AuracleCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auracle/$id': {
      id: '/auracle/$id'
      path: '/auracle/$id'
      fullPath: '/auracle/$id'
      preLoaderRoute: typeof AuracleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura/$id': {
      id: '/aura/$id'
      path: '/aura/$id'
      fullPath: '/aura/$id'
      preLoaderRoute: typeof AuraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$handle': {
      id: '/artist/$handle'
      path: '/artist/$handle'
      fullPath: '/artist/$handle'
      preLoaderRoute: typeof ArtistHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  FarmRoute: FarmRoute,
  GeneratingRoute: GeneratingRoute,
  OnboardingRoute: OnboardingRoute,
  ArtistHandleRoute: ArtistHandleRoute,
  AuraIdRoute: AuraIdRoute,
  AuracleIdRoute: AuracleIdRoute,
  AuracleCreateRoute: AuracleCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
